version: '3'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    #ports:
    #  - "53:53/tcp"
    #  - "53:53/udp"
    #  - "67:67/udp"
    #  - "80:80/tcp"
    #  - "443:443/tcp"
    environment: 
      TZ: 'Europe/Stockholm'
    volumes: 
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      - './var-log/pihole.log:/var/log/pihole.log'
    #dns:
    #  - 127.0.0.1
    #  - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped